#!/usr/bin/env python3
"""Codex proxy: ensures collector is running, then execs the real codex binary.

Replaces codex-tracing/scripts/codex_proxy.sh. Registered as the
``arize-codex-proxy`` CLI entry point so the installer can symlink or alias
``codex`` → ``arize-codex-proxy``.

The bash version relied on installer-templated placeholders (__REAL_CODEX__,
etc.).  This Python version discovers the real binary dynamically at runtime by
scanning PATH and skipping itself, which is more robust and doesn't require
installer templating.
"""

import os
import subprocess
import sys
from pathlib import Path


def _find_real_codex() -> "Path | None":
    """Find the real codex binary on PATH, skipping the proxy itself.

    Strategy:
    1. Get this script's resolved path (handles symlinks).
    2. Scan PATH entries for 'codex' (or 'codex.exe' on Windows).
    3. Skip any that resolve to the same path as this script.
    4. Return the first non-self match, or None.
    """
    self_path = Path(__file__).resolve()
    # Also check the entry-point wrapper that pip installs
    self_entry = Path(sys.argv[0]).resolve() if sys.argv else None

    codex_name = "codex.exe" if os.name == "nt" else "codex"
    for dir_str in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(dir_str) / codex_name
        if not candidate.is_file():
            continue
        resolved = candidate.resolve()
        if resolved == self_path or resolved == self_entry:
            continue
        if os.access(candidate, os.X_OK):
            return candidate
    return None


def main() -> None:
    """Codex proxy entry point.  Ensures collector running, then execs real codex."""
    # 1. Load env file & ensure collector (matches bash lines 12-24)
    try:
        env_file = Path.home() / ".codex" / "arize-env.sh"
        if env_file.is_file():
            _load_env_file(env_file)

        from core.collector_ctl import collector_ensure  # noqa: E402
        collector_ensure()
    except Exception:
        pass  # Never prevent codex from starting

    # 2. Find the real codex binary
    real_codex = _find_real_codex()
    if not real_codex:
        print("[arize] Could not find real codex binary on PATH", file=sys.stderr)
        sys.exit(1)

    # 3. exec replaces this process (matches bash ``exec "$REAL_CODEX" "$@"``)
    if os.name == "nt":
        # Windows: no exec, use subprocess with exit code passthrough
        result = subprocess.run([str(real_codex)] + sys.argv[1:])
        sys.exit(result.returncode)
    else:
        os.execvp(str(real_codex), [str(real_codex)] + sys.argv[1:])


def _load_env_file(path: Path) -> None:
    """Source a simple KEY=VALUE env file (no shell expansion).

    Reads lines of the form ``export KEY=VALUE`` or ``KEY=VALUE`` and sets
    them in ``os.environ``.  This is intentionally minimal — it covers the
    env files generated by the installer without requiring a shell.
    """
    try:
        text = path.read_text()
    except OSError:
        return
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip("\"'")
        if key:
            os.environ[key] = value


if __name__ == "__main__":
    main()
