#!/usr/bin/env python3
"""Codex proxy: ensures buffer service is running, then execs the real codex binary.

Replaces tracing/codex/scripts/codex_proxy.sh. Registered as the
``arize-codex-proxy`` CLI entry point so the installer can symlink or alias
``codex`` → ``arize-codex-proxy``.

The bash version relied on installer-templated placeholders (__REAL_CODEX__,
etc.).  This Python version discovers the real binary dynamically at runtime by
scanning PATH and skipping itself, which is more robust and doesn't require
installer templating.

NOTE: This module deliberately avoids ``pathlib`` at the top level. The import
of ``pathlib`` pulls in ``ntpath`` which can deadlock on the CPython import
lock when another Python process (e.g. the collector) is starting concurrently.
All path operations use ``os.path`` instead.
"""

import os
import subprocess
import sys


def _codex_candidate_names() -> list[str]:
    """Return executable names a shell may resolve for ``codex``."""
    if os.name != "nt":
        return ["codex"]

    names = ["codex"]
    pathext = os.environ.get("PATHEXT", ".COM;.EXE;.BAT;.CMD")
    for ext in pathext.split(";"):
        ext = ext.strip()
        if not ext:
            continue
        if not ext.startswith("."):
            ext = "." + ext
        name = "codex" + ext.lower()
        if name not in names:
            names.append(name)
    return names


def _is_arize_codex_shim(path: str) -> bool:
    """Return True when *path* is the installer-managed tracing shim."""
    try:
        with open(path, encoding="utf-8", errors="ignore") as f:
            text = f.read(4096)
    except OSError:
        return False
    return "arize-codex-proxy" in text and "Arize Codex proxy shim" in text


def _find_real_codex() -> "str | None":
    """Find the real codex binary on PATH, skipping the proxy itself.

    Strategy:
    1. Get this script's resolved path (handles symlinks).
    2. Scan PATH entries for 'codex' (or PATHEXT variants on Windows).
    3. Skip any that resolve to the same path as this script or the
       installer-managed shim.
    4. Return the first non-self match, or None.
    """
    self_path = os.path.realpath(__file__)
    # Also check the entry-point wrapper that pip installs
    self_entry = os.path.realpath(sys.argv[0]) if sys.argv else None

    path_separator = ";" if os.name == "nt" else os.pathsep
    for dir_str in os.environ.get("PATH", "").split(path_separator):
        for codex_name in _codex_candidate_names():
            candidate = os.path.join(dir_str, codex_name)
            if not os.path.isfile(candidate):
                continue
            resolved = os.path.realpath(candidate)
            if resolved == self_path or resolved == self_entry:
                continue
            if _is_arize_codex_shim(candidate):
                continue
            if os.access(candidate, os.X_OK):
                return candidate
    return None


def _load_env_file(path: str) -> None:
    """Source a simple KEY=VALUE env file (no shell expansion).

    Reads lines of the form ``export KEY=VALUE`` or ``KEY=VALUE`` and sets
    them in ``os.environ``.  This is intentionally minimal — it covers the
    env files generated by the installer without requiring a shell.
    """
    try:
        with open(path) as f:
            text = f.read()
    except OSError:
        return
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :]
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip("\"'")
        if key:
            os.environ[key] = value


def _quick_health_check(host: str = "127.0.0.1", port: int = 4318) -> bool:
    """Fast HTTP health check with hard timeout. No heavy imports."""
    import urllib.request

    try:
        urllib.request.urlopen(f"http://{host}:{port}/health", timeout=1)
        return True
    except Exception:
        return False


def main() -> None:
    """Codex proxy entry point.  Ensures buffer service running, then execs real codex."""
    # 1. Load env file & ensure buffer service (matches bash lines 12-24)
    try:
        env_file = os.path.join(os.path.expanduser("~"), ".codex", "arize-env.sh")
        if os.path.isfile(env_file):
            _load_env_file(env_file)

        # Fast path: if buffer service is already healthy, skip heavy imports
        if not _quick_health_check():
            from tracing.codex.codex_buffer_ctl import buffer_ensure  # noqa: E402

            buffer_ensure()
    except Exception:
        pass  # Never prevent codex from starting

    # 2. Find the real codex binary
    real_codex = _find_real_codex()
    if not real_codex:
        print("[arize] Could not find real codex binary on PATH", file=sys.stderr)
        sys.exit(1)

    # 3. For exec mode: wrap so we can drain the buffer after codex exits.
    #    For interactive mode: exec replaces this process.
    is_exec = "exec" in sys.argv[1:]

    if is_exec or os.name == "nt":
        result = subprocess.run([real_codex] + sys.argv[1:])
        if is_exec:
            # Import scoped here: drain_idle pulls in core.common + OTLP span
            # building (~34 modules). Interactive codex doesn't need it, so we
            # defer the cost to exec-mode only. Same fast-path pattern as line 96.
            try:
                from tracing.codex.hooks.handlers import drain_idle

                drain_idle()
            except Exception as e:
                # Never fail the proxy, but surface the failure for debugging.
                print(f"[arize] drain_idle failed: {e}", file=sys.stderr)
        sys.exit(result.returncode)
    else:
        os.execvp(real_codex, [real_codex] + sys.argv[1:])


if __name__ == "__main__":
    main()
